import random

WIN_WIDTH= 800
WIN_HEIGHT= 640
TILESIZE = 95
FPS = 60

ENEMY_SPEED = 2
ENEMY_LAYER=2
PLAYER_LAYER=4
BLOCK_LAYER=1
PLAYER_SPEED = 3
GROUND_LAYER = 1

RED = (255,0,0)
BLACK =(0,0,0)
BLUE = (0,0,255)
GREEN = (0,255,0)
WHITE =(255,255,255)


tilemap = [
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'B.R....RRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR..B',
    'B...P.RR...RRRRRRRRRRRRRRR....R....RRRRRRRRRRRRRRRRRRRR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRR....R....RRRRRRRRRRRRRRRRRRRR...B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR....R....RRRRRRRRRRRRRRRRRRRR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R..B',
    'B..RRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRR..B',
    'B.R....RRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B.....RR...RRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR...B',
    'B..RRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR...B',
    'B..RRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR....B',
    'B.RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R...B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRR.B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRRR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR...B',
    'B..RRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R...B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B.R....RRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B.....RR...RRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR....R....RRRRRRRRRRRRRRRRRRRR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR...B',
    'B.R....RRRRRRRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR...B',
    'B.....RR...RRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRR....R....RRRRRRRRRRRRRRRRRRRR...B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR...B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR....B',
    'B.R....RRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR....B',
    'B.....RR...RRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR....B',
    'B..RRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR....B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R.B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RRR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R...B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R...B',
    'B..RRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B.R....RRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR..B',
    'B.....RR...RRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R...B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRR...R....RRRRRRRRRRRRRRRRRRRR....B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR..R....RRRRRRRRRRRRRRRRRRRR....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..RR.B',
    'B.RRRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R..B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR.....B',
    'B..RRRRRRRRRRRRRRRRRRRRRRR.R....RRRRRRRRRRRRRRRRRRRR..R..B',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]
